#!/bin/sh
# toggle touch pad

isOn=`xfconf-query -c pointers -p /SynPS2_Synaptics_TouchPad/Properties/Device_Enabled -v | tail -c 2`
iconEnabled='input-touchpad-symbolic'
iconDisabled='touchpad-disabled-symbolic'

case "$isOn" in
    0)
        notify-send --icon=$iconEnabled --expire-time=2000 "Touchpad [ON]" "Your touchpad is now enabled"
        xfconf-query -c pointers -p /SynPS2_Synaptics_TouchPad/Properties/Device_Enabled -v -s 1
        ;;
    1)
        notify-send --icon=$iconDisabled --expire-time=2000 "Touchpad [OFF]" "Your touchpad is now disabled"
        xfconf-query -c pointers -p /SynPS2_Synaptics_TouchPad/Properties/Device_Enabled -v -s 0
        ;;
    *)
        notify-send --icon=$iconEnabled --expire-time=10000  "Error: Touchpad device enabled says: $isOn."
        ;;
esac

