#!/bin/bash

change_mirror() {
    cp /usr/share/xbps.d/*-repository-*.conf /etc/xbps.d/
    sed -i 's|https://repo-default.voidlinux.org/|'$1'|g' /etc/xbps.d/*-repository-*.conf
}

if [[ $# -eq 1 ]]; then
    if [[ -d /etc/xbps.d ]]; then
       change_mirror $1
       echo "Mirror changed"
    fi
fi
