#!/bin/bash

if [[ $EUID = 0 ]]; then
    echo "Não é recomendado executar esse script como super usuário."
fi

if [[ -f "/usr/bin/code" ]]; then
    code --install-extension 2gua.rainbow-brackets
    code --install-extension ecmel.vscode-html-css
    code --install-extension Tyriar.lorem-ipsum
    code --install-extension pranaygp.vscode-css-peek
    code --install-extension ritwickdey.LiveServer
    code --install-extension xabikos.JavaScriptSnippets
    code --install-extension formulahendry.code-runner
else if [[ -f "/usr/bin/code-oss" ]]; then
    code-oss --install-extension ecmel.vscode-html-css
    code-oss --install-extension 2gua.rainbow-brackets
    code-oss --install-extension Tyriar.lorem-ipsum
    code-oss --install-extension pranaygp.vscode-css-peek
    code-oss --install-extension ritwickdey.LiveServer
    code-oss --install-extension xabikos.JavaScriptSnippets
    code-oss --install-extension formulahendry.code-runner
    fi
fi
