#!/bin/bash

swapfile="/swap/swapfile"

genswap () {
    truncate -s 0 $swapfile && echo "command truncate exeuted"
    chattr +C $swapfile && echo "command chattr executed"
    btrfs property set $swapfile compression none && echo "btrfs property executed"
    fallocate -l 2G $swapfile && echo "fallocate executed"
    chmod 600 $swapfile && echo "permission set"
    lsattr $swapfile && echo "lsattr executed"
    mkswap $swapfile && echo "mkswap executed"
    swapon $swapfile && echo "swapon executed"
}

if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root" 2>&1
    exit 1
else
    if [[ -f $swapfile ]]; then
        swapoff $swapfile && echo "/swap/swapfile is turned off"
        rm $swapfile && echo "$swapfile deleted"
        genswap
    else
        genswap
    fi
fi
